name: Next CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd ~/aipex-main/ApexAI
          git stash
          git pull origin main
          git stash pop
          npm install
          npx prisma migrate deploy
          npx prisma generate
          pm2 stop all
          npm run build
          pm2 start all
